
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Afghanistan', 'AF');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Albania', 'AL');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Algeria', 'DZ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('American Samoa', 'AS');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Andorra', 'AD');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Angola', 'AO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Anguilla', 'AI');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Antarctica', 'AQ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Antigua and Barbuda', 'AG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Argentina', 'AR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Armenia', 'AM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Aruba', 'AW');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Australia', 'AU');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Austria', 'AT');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Azerbaijan', 'AZ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Bahamas', 'BS');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Bahrain', 'BH');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Bangladesh', 'BD');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Barbados', 'BB');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Belarus', 'BY');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Belgium', 'BE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Belize', 'BZ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Benin', 'BJ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Bermuda', 'BM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Bhutan', 'BT');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Bosnia and Herzegovina', 'BA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Botswana', 'BW');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Bouvet Island', 'BV');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Brazil', 'BR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('British Indian Ocean Territory', 'IO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Brunei Darussalam', 'BN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Bulgaria', 'BG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Burkina Faso', 'BF');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Burundi', 'BI');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Cambodia', 'KH');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Cameroon', 'CM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Canada', 'CA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Cape Verde', 'CV');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Cayman Islands', 'KY');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Central African Republic', 'CF');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Chad', 'TD');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Chile', 'CL');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('China', 'CN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Christmas Island', 'CX');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Cocos (Keeling) Islands', 'CC');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Colombia', 'CO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Comoros', 'KM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Congo', 'CG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Cook Islands', 'CK');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Costa Rica', 'CR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Croatia', 'HR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Cuba', 'CU');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Cyprus', 'CY');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Czech Republic', 'CZ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Denmark', 'DK');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Djibouti', 'DJ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Dominica', 'DM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Dominican Republic', 'DO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Ecuador', 'EC');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Egypt', 'EG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('El Salvador', 'SV');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Equatorial Guinea', 'GQ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Eritrea', 'ER');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Estonia', 'EE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Ethiopia', 'ET');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Falkland Islands (Malvinas)' ,'FK');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Faroe Islands', 'FO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Fiji', 'FJ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Finland', 'FI');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('France', 'FR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('French Guiana', 'GF');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('French Polynesia', 'PF');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('French Southern Territories', 'TF');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Gabon', 'GA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Gambia', 'GM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Georgia', 'GE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Germany', 'DE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Ghana', 'GH');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Gibraltar', 'GI');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Greece', 'GR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Greenland', 'GL');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Grenada', 'GD');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Guadeloupe', 'GP');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Guam', 'GU');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Guatemala', 'GT');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Guernsey', 'GG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Guinea', 'GN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Guinea-Bissau', 'GW');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Guyana', 'GY');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Haiti', 'HT');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Heard Island and McDonald Islands', 'HM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Holy See (Vatican City State)' ,'VA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Honduras', 'HN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Hong Kong', 'HK');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Hungary', 'HU');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Iceland', 'IS');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('India', 'IN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Indonesia', 'ID');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Iraq', 'IQ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Ireland', 'IE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Isle of Man', 'IM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Israel', 'IL');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Italy', 'IT');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Jamaica', 'JM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Japan', 'JP');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Jersey', 'JE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Jordan', 'JO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Kazakhstan', 'KZ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Kenya', 'KE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Kiribati', 'KI');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Kuwait', 'KW');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Kyrgyzstan', 'KG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Lao Peoples Democratic Republic', 'LA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Latvia', 'LV');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Lebanon', 'LB');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Lesotho', 'LS');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Liberia', 'LR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Libya', 'LY');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Liechtenstein', 'LI');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Lithuania', 'LT');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Luxembourg', 'LU');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Macao', 'MO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Madagascar', 'MG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Malawi', 'MW');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Malaysia', 'MY');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Maldives', 'MV');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Mali', 'ML');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Malta', 'MT');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Marshall Islands', 'MH');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Martinique', 'MQ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Mauritania', 'MR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Mauritius', 'MU');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Mayotte', 'YT');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Mexico', 'MX');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Monaco', 'MC');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Mongolia', 'MN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Montenegro', 'ME');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Montserrat', 'MS');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Morocco', 'MA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Mozambique', 'MZ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Myanmar', 'MM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Namibia', 'NA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Nauru', 'NR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Nepal', 'NP');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Netherlands', 'NL');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('New Caledonia', 'NC');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('New Zealand', 'NZ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Nicaragua', 'NI');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Niger', 'NE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Nigeria', 'NG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Niue', 'NU');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Norfolk Island', 'NF');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Northern Mariana Islands', 'MP');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Norway', 'NO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Oman', 'OM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Pakistan', 'PK');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Palau', 'PW');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Panama', 'PA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Papua New Guinea', 'PG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Paraguay', 'PY');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Peru', 'PE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Philippines', 'PH');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Pitcairn', 'PN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Poland', 'PL');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Portugal', 'PT');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Puerto Rico', 'PR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Qatar', 'QA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Romania', 'RO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Russian Federation', 'RU');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Rwanda', 'RW');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Saint Kitts and Nevis', 'KN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Saint Lucia', 'LC');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Saint Martin (French part)' ,'MF');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Saint Pierre and Miquelon', 'PM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Saint Vincent and the Grenadines', 'VC');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Samoa', 'WS');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('San Marino', 'SM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Sao Tome and Principe', 'ST');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Saudi Arabia', 'SA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Senegal', 'SN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Serbia', 'RS');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Seychelles', 'SC');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Sierra Leone', 'SL');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Singapore', 'SG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Sint Maarten (Dutch part)' ,'SX');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Slovakia', 'SK');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Slovenia', 'SI');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Solomon Islands', 'SB');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Somalia', 'SO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('South Africa', 'ZA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('South Georgia and the South Sandwich Islands', 'GS');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('South Sudan', 'SS');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Spain', 'ES');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Sri Lanka', 'LK');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Sudan', 'SD');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Suriname', 'SR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Svalbard and Jan Mayen', 'SJ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Swaziland', 'SZ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Sweden', 'SE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Switzerland', 'CH');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Syrian Arab Republic', 'SY');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Tajikistan', 'TJ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Thailand', 'TH');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Timor-Leste', 'TL');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Togo', 'TG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Tokelau', 'TK');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Tonga', 'TO');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Trinidad and Tobago', 'TT');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Tunisia', 'TN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Turkey', 'TR');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Turkmenistan', 'TM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Turks and Caicos Islands', 'TC');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Tuvalu', 'TV');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Uganda', 'UG');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Ukraine', 'UA');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('United Arab Emirates', 'AE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('United Kingdom', 'GB');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('United States', 'US');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('United States Minor Outlying Islands', 'UM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Uruguay', 'UY');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Uzbekistan', 'UZ');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Vanuatu', 'VU');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Viet Nam', 'VN');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Wallis and Futuna', 'WF');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Western Sahara', 'EH');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Yemen', 'YE');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Zambia', 'ZM');
INSERT INTO master.dbo.countries (Name, ISO) VALUES ('Zimbabwe', 'ZW');