/*
--
--	This script fills countries table
--
*/

INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Afghanistan', 'AF')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Albania', 'AL')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Algeria', 'DZ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('American Samoa', 'AS')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Andorra', 'AD')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Angola', 'AO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Anguilla', 'AI')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Antarctica', 'AQ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Antigua and Barbuda', 'AG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Argentina', 'AR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Armenia', 'AM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Aruba', 'AW')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Australia', 'AU')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Austria', 'AT')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Azerbaijan', 'AZ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Bahamas', 'BS')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Bahrain', 'BH')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Bangladesh', 'BD')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Barbados', 'BB')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Belarus', 'BY')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Belgium', 'BE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Belize', 'BZ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Benin', 'BJ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Bermuda', 'BM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Bhutan', 'BT')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Bosnia and Herzegovina', 'BA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Botswana', 'BW')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Bouvet Island', 'BV')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Brazil', 'BR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('British Indian Ocean Territory', 'IO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Brunei Darussalam', 'BN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Bulgaria', 'BG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Burkina Faso', 'BF')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Burundi', 'BI')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Cambodia', 'KH')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Cameroon', 'CM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Canada', 'CA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Cape Verde', 'CV')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Cayman Islands', 'KY')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Central African Republic', 'CF')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Chad', 'TD')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Chile', 'CL')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('China', 'CN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Christmas Island', 'CX')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Cocos (Keeling) Islands', 'CC')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Colombia', 'CO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Comoros', 'KM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Congo', 'CG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Cook Islands', 'CK')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Costa Rica', 'CR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Croatia', 'HR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Cuba', 'CU')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Cyprus', 'CY')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Czech Republic', 'CZ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Denmark', 'DK')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Djibouti', 'DJ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Dominica', 'DM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Dominican Republic', 'DO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Ecuador', 'EC')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Egypt', 'EG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('El Salvador', 'SV')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Equatorial Guinea', 'GQ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Eritrea', 'ER')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Estonia', 'EE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Ethiopia', 'ET')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Falkland Islands (Malvinas)' ,'FK')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Faroe Islands', 'FO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Fiji', 'FJ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Finland', 'FI')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('France', 'FR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('French Guiana', 'GF')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('French Polynesia', 'PF')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('French Southern Territories', 'TF')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Gabon', 'GA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Gambia', 'GM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Georgia', 'GE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Germany', 'DE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Ghana', 'GH')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Gibraltar', 'GI')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Greece', 'GR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Greenland', 'GL')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Grenada', 'GD')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Guadeloupe', 'GP')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Guam', 'GU')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Guatemala', 'GT')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Guernsey', 'GG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Guinea', 'GN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Guinea-Bissau', 'GW')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Guyana', 'GY')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Haiti', 'HT')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Heard Island and McDonald Islands', 'HM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Holy See (Vatican City State)' ,'VA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Honduras', 'HN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Hong Kong', 'HK')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Hungary', 'HU')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Iceland', 'IS')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('India', 'IN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Indonesia', 'ID')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Iraq', 'IQ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Ireland', 'IE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Isle of Man', 'IM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Israel', 'IL')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Italy', 'IT')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Jamaica', 'JM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Japan', 'JP')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Jersey', 'JE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Jordan', 'JO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Kazakhstan', 'KZ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Kenya', 'KE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Kiribati', 'KI')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Kuwait', 'KW')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Kyrgyzstan', 'KG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Lao Peoples Democratic Republic', 'LA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Latvia', 'LV')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Lebanon', 'LB')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Lesotho', 'LS')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Liberia', 'LR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Libya', 'LY')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Liechtenstein', 'LI')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Lithuania', 'LT')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Luxembourg', 'LU')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Macao', 'MO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Madagascar', 'MG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Malawi', 'MW')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Malaysia', 'MY')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Maldives', 'MV')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Mali', 'ML')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Malta', 'MT')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Marshall Islands', 'MH')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Martinique', 'MQ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Mauritania', 'MR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Mauritius', 'MU')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Mayotte', 'YT')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Mexico', 'MX')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Monaco', 'MC')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Mongolia', 'MN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Montenegro', 'ME')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Montserrat', 'MS')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Morocco', 'MA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Mozambique', 'MZ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Myanmar', 'MM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Namibia', 'NA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Nauru', 'NR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Nepal', 'NP')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Netherlands', 'NL')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('New Caledonia', 'NC')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('New Zealand', 'NZ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Nicaragua', 'NI')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Niger', 'NE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Nigeria', 'NG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Niue', 'NU')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Norfolk Island', 'NF')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Northern Mariana Islands', 'MP')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Norway', 'NO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Oman', 'OM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Pakistan', 'PK')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Palau', 'PW')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Panama', 'PA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Papua New Guinea', 'PG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Paraguay', 'PY')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Peru', 'PE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Philippines', 'PH')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Pitcairn', 'PN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Poland', 'PL')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Portugal', 'PT')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Puerto Rico', 'PR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Qatar', 'QA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Romania', 'RO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Russian Federation', 'RU')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Rwanda', 'RW')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Saint Kitts and Nevis', 'KN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Saint Lucia', 'LC')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Saint Martin (French part)' ,'MF')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Saint Pierre and Miquelon', 'PM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Saint Vincent and the Grenadines', 'VC')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Samoa', 'WS')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('San Marino', 'SM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Sao Tome and Principe', 'ST')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Saudi Arabia', 'SA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Senegal', 'SN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Serbia', 'RS')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Seychelles', 'SC')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Sierra Leone', 'SL')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Singapore', 'SG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Sint Maarten (Dutch part)' ,'SX')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Slovakia', 'SK')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Slovenia', 'SI')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Solomon Islands', 'SB')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Somalia', 'SO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('South Africa', 'ZA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('South Georgia and the South Sandwich Islands', 'GS')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('South Sudan', 'SS')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Spain', 'ES')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Sri Lanka', 'LK')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Sudan', 'SD')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Suricountry_name', 'SR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Svalbard and Jan Mayen', 'SJ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Swaziland', 'SZ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Sweden', 'SE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Switzerland', 'CH')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Syrian Arab Republic', 'SY')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Tajikistan', 'TJ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Thailand', 'TH')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Timor-Leste', 'TL')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Togo', 'TG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Tokelau', 'TK')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Tonga', 'TO')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Trinidad and Tobago', 'TT')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Tunisia', 'TN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Turkey', 'TR')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Turkmenistan', 'TM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Turks and Caicos Islands', 'TC')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Tuvalu', 'TV')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Uganda', 'UG')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Ukraine', 'UA')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('United Arab Emirates', 'AE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('United Kingdom', 'GB')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('United States', 'US')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('United States Minor Outlying Islands', 'UM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Uruguay', 'UY')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Uzbekistan', 'UZ')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Vanuatu', 'VU')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Viet Nam', 'VN')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Wallis and Futuna', 'WF')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Western Sahara', 'EH')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Yemen', 'YE')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Zambia', 'ZM')
INSERT INTO master.dbo.countries (country_name, country_iso) VALUES ('Zimbabwe', 'ZW')